[package]
categories = [ "command-line-utilities" ]
description = "Install and manage dev tools."
edition = "2021"
license = "MIT"
name = "released"
repository = "https://github.com/dsully/released"
version = "0.0.1"

[profile.release]
incremental = true
lto = true
opt-level = 3

[profile.dev]
incremental = true

# The profile that 'cargo dist' will build with
[profile.dist]
inherits = "release"
lto = "thin"

[dependencies]
anyhow = { version = "1.0", features = [ "backtrace" ] }
async-trait = "0.1.74"
clap = { version = "4.4", default-features = false, features = [
    "cargo",
    "color",
    "derive",
    "suggestions",
    "wrap_help",
] }
clap-verbosity-flag = "2.0"
clap_complete = "4.4"
compress-tools = "0.14.3"
config = { version = "0.13.3", default-features = false, features = [ "toml" ] }
console = "0.15.7"
ctrlc = { version = "3.4.1", features = [ "termination" ] }
futures = "0.3.28"
indicatif = "0.17"
infer = "0.15.0"
octocrab = "0.31"
pluralizer = "0.4.0"
regex = "1.10"
reqwest = { version = "0.11", features = [ "stream" ] }
semver = "1.0"
serde = { version = "1.0", features = [ "derive" ] }
serde_derive = "1.0"
serde_json = "1.0"
shadow-rs = { version = "0.24", default-features = false }
skim = "0.10"
strfmt = "0.2.4"
tabled = { version = "0.14", features = [ "std" ] }
tempfile = "3.8.0"
thiserror = "1.0"
tokio = { version = "1.33.0", features = [
    "fs",
    "macros",
    "net",
    "rt",
    "rt-multi-thread",
] }
toml = { version = "0.8", features = [ "preserve_order" ] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = [ "env-filter" ] }
walkdir = "2.4"
xdg = "2.5.2"

[build-dependencies]
shadow-rs = { version = "0.24", default-features = false }

# Config for 'cargo dist'
[workspace.metadata.dist]
# The preferred cargo-dist version to use in CI (Cargo.toml SemVer syntax)
cargo-dist-version = "0.3.1"
# CI backends to support
ci = ["github"]
# The installers to generate for each app
installers = ["homebrew"]
# A GitHub repo to push Homebrew formulas to
tap = "dsully/homebrew-tap"
# Target platforms to build apps for (Rust target-triple syntax)
targets = ["x86_64-unknown-linux-gnu", "aarch64-apple-darwin"]
# Publish jobs to run in CI
publish-jobs = ["homebrew"]
# Publish jobs to run in CI
pr-run-mode = "plan"
