[package]
categories = [ "command-line-utilities" ]
description = "Install and manage dev tools."
edition = "2021"
license = "MIT"
name = "released"
repository = "https://github.com/dsully/released"
version = "0.0.1"

[profile.release]
incremental = true
lto = true
opt-level = 3

[profile.dev]
incremental = true

[dependencies]
anyhow = "1.0"
async-trait = "0.1.73"
clap = { version = "4.4", features = [
    "cargo",
    "color",
    "derive",
    "suggestions",
    "wrap_help",
] }
clap-verbosity-flag = "2.0"
clap_complete = "4.4"
compress-tools = "0.14.3"
config = { version = "0.13.3", default-features = false, features = [ "toml" ] }
console = "0.15.7"
ctrlc = { version = "3.4.1", features = ["termination"] }
futures = "0.3.28"
indicatif = "0.17"
infer = "0.15.0"
octocrab = "0.25"
pluralizer = "0.4.0"
regex = "1.9"
reqwest = { version = "0.11", features = ["stream"] }
semver = "1.0"
serde = { version = "1.0", features = [ "derive" ] }
serde_json = "1.0"
shadow-rs = { version = "0.24", default-features = false }
skim = "0.10"
tabled = { version = "0.14", features = [ "std" ] }
tempfile = "3.8.0"
thiserror = "1.0"
tokio = { version = "1.32.0", features = [
    "fs",
    "macros",
    "net",
    "rt",
    "rt-multi-thread",
] }
toml = { version = "0.8", features = [ "preserve_order" ] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = [ "env-filter" ] }
walkdir = "2.4"
xdg = "2.5.2"

[build-dependencies]
shadow-rs = { version = "0.24", default-features = false }
